Feature hero
Ljuzifer/demonic-chocolate pull request #13
Opened 2023-04-08 18:06 UTC by IrinaPost12

Мобілка зі зламаним контейнером.
Як виправити?

2023-04-08 23:15 UTC, Ljuzifer requested changes

2023-04-08 23:15 UTC, Ljuzifer commented on src/css/hero.css
> +        max-width: 100%;
знов навіщо перебила глобальне правило?

2023-04-08 23:15 UTC, Ljuzifer commented on src/css/hero.css
> +}
взагалі навіщо ти собі покопіювала медіа-запити, вони  так працюють??

2023-04-08 23:15 UTC, Ljuzifer commented on src/css/hero.css
> +    display: flex;
а нашо тут флекс?

2023-04-08 23:15 UTC, Ljuzifer commented on src/css/hero.css
> +    width: 100%;
краще мін-відз

2023-04-08 23:15 UTC, Ljuzifer commented on src/css/hero.css
> +    margin-top: 32px;
тут марджин-боттом у кнопки зверху повинен бути

2023-04-08 23:15 UTC, Ljuzifer commented on src/css/hero.css
> +    margin-bottom: 20px;
авто

2023-04-08 23:15 UTC, Ljuzifer commented on src/css/hero.css
> +    margin-left: 20px;
правий і лівий авто-марджини

2023-04-09 09:32 UTC, IrinaPost12 commented on src/css/hero.css
> +.visually-hidden {
видалила

2023-04-09 09:33 UTC, IrinaPost12 commented on src/css/hero.css
> +.hero-button-how-it’s-made {
перейменувала

2023-04-09 09:34 UTC, IrinaPost12 commented on src/css/hero.css
> +    cursor: pointer;
видалила

2023-04-09 09:36 UTC, IrinaPost12 commented on src/css/hero.css
> +    width: 120px;
виправила в .hero-button-buy-now і .hero-button-how-its-made

2023-04-09 09:37 UTC, IrinaPost12 commented on src/css/hero.css
> +    background: var(--accent-main-color);
виправила

2023-04-09 09:39 UTC, IrinaPost12 commented on src/css/hero.css
> +    border-radius: 100px;
взяла з макета. Але ж працює). Виправила на 50%.

2023-04-09 09:40 UTC, IrinaPost12 commented on src/css/hero.css
> +    cursor: pointer;
видалила, де повторювалися значення цих стилів

2023-04-09 09:42 UTC, IrinaPost12 commented on src/css/hero.css
> +    color: #FFFFFF;
виправлено

2023-04-09 09:44 UTC, IrinaPost12 commented on src/css/hero.css
> +        max-width: 100%;
це я намагалася пофіксити проблему, що з'явилася з контейнером. Текст став виходити за межі контейнера. Повернула глобальне правило.

2023-04-09 09:46 UTC, IrinaPost12 commented on src/css/hero.css
> +}
я тут не зрозуміла. Потрібно переговорити.

2023-04-09 09:52 UTC, IrinaPost12 commented on src/css/hero.css
> +    display: flex;
то вже мабуть по інерції) Видалила

2023-04-09 09:53 UTC, IrinaPost12 commented on src/css/hero.css
> +    width: 100%;
виправила

2023-04-09 09:54 UTC, IrinaPost12 commented on src/css/hero.css
> +    margin-top: 32px;
він там і є, 20рх

2023-04-09 09:58 UTC, IrinaPost12 commented on src/css/hero.css
> +    margin-bottom: 20px;
як auto - то все зсуває в кучу. Поки не виправляла.

2023-04-09 10:41 UTC, IrinaPost12 commented on src/css/hero.css
> +    margin-left: 20px;
ок.

2023-04-09 10:58 UTC, Ljuzifer approved these changes

2023-04-09 10:58 UTC, merged