Feature advantages
Ljuzifer/demonic-chocolate pull request #14
Opened 2023-04-08 19:26 UTC by Halyna18

2023-04-08 22:39 UTC, Ljuzifer requested changes

2023-04-08 22:39 UTC, Ljuzifer commented on src/partials/main-advantages.html
> -<section class="thumb">
я ж казав клас thumb не видаляти, він глобально робить відступи між контенерами

2023-04-08 22:39 UTC, Ljuzifer commented on src/css/advantages.css
> +.advantages {
можна ж було просто використовувати клас thumb

2023-04-08 22:39 UTC, Ljuzifer commented on src/css/advantages.css
> +@media screen and (min-width: 375px) {
не залишайй порожній селектор\медіазапит

2023-04-08 22:39 UTC, Ljuzifer commented on src/css/advantages.css
> +.advantages-item {
знов порожній

2023-04-08 22:39 UTC, Ljuzifer commented on src/css/advantages.css
> +.advantages-item-icon {
знов порожній

2023-04-09 15:16 UTC, Halyna18 commented on src/partials/main-advantages.html
> -<section class="thumb">
в класі advantages він зайвий там колір фону чорний, коли я лишаю клас thumb секція йде вже не за макетом

2023-04-09 15:51 UTC, Ljuzifer approved these changes

2023-04-09 15:52 UTC, merged