Feature subscribe modal
Ljuzifer/demonic-chocolate pull request #26
Opened 2023-04-09 22:22 UTC by Halyna18

Modal. Explore our new chocolate first!

2023-04-09 23:13 UTC, Ljuzifer requested changes

2023-04-09 23:13 UTC, Ljuzifer commented on src/css/subscribe.css
> +    min-width: 538px;
max-width

2023-04-09 23:13 UTC, Ljuzifer commented on src/css/subscribe.css
> +  min-width: 311px;
max-width

2023-04-09 23:13 UTC, Ljuzifer commented on src/css/subscribe.css
> +  background: var(--text-second-color);
background-color

2023-04-09 23:13 UTC, Ljuzifer commented on src/css/subscribe.css
> +  background: rgba(252, 241, 224, 1);
background-color

2023-04-10 06:41 UTC, Halyna18 commented on src/css/subscribe.css
> +    min-width: 538px;
при max-width все ламається

2023-04-10 11:46 UTC, Ljuzifer commented on src/css/subscribe.css
> +    min-width: 538px;
а можеш скрін зробить як було і як ламається

2023-04-10 16:20 UTC, Ljuzifer approved these changes

2023-04-10 16:36 UTC, Ljuzifer approved these changes

2023-04-10 16:36 UTC, merged