feature/subscribe
Ljuzifer/demonic-chocolate pull request #7
Opened 2023-04-07 20:00 UTC by LiliiaAparina

Add markup for main-subscribe, styles for subscribe.css

2023-04-07 21:31 UTC, Ljuzifer requested changes
Верни класс, або свій заміни якщо прописвала відступи. Хоч і не критично, але буде гарніше якщо глобально буде прописано. А так наче норм))

2023-04-07 21:31 UTC, Ljuzifer commented on src/partials/main-subscribe.html
> -<section>
ти видалила заготовку!? там клас thumb - він важливий, поверни, він відповідав за відступи між контейнерами

2023-04-07 21:31 UTC, Ljuzifer commented on src/css/subscribe.css
> +    border: 0;
може краще none а не 0? ну це таке...

2023-04-07 22:21 UTC, LiliiaAparina commented on src/partials/main-subscribe.html
> -<section>
я не видаляла бо в моїй заготовці thumb не стояв. напевно тому що в мене нема нижнього марджина, так?

2023-04-07 23:22 UTC, Ljuzifer commented on src/partials/main-subscribe.html
> -<section>
логічно))) це мене вже поплавило... просто дехто повидаляв, хоч я і казав не трогать))

2023-04-08 00:33 UTC, Ljuzifer approved these changes

2023-04-08 00:33 UTC, merged